stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: req.sotcbb.org:5000/zabbix/zabbix-agent:0.0.10
      pushRemote: true
      registry: http://10.10.0.192:5000
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
